var annotated_dup =
[
    [ "rm", "namespacerm.html", [
      [ "detail", "namespacerm_1_1detail.html", [
        [ "NonCopyable", "classrm_1_1detail_1_1NonCopyable.html", "classrm_1_1detail_1_1NonCopyable" ]
      ] ],
      [ "device", "namespacerm_1_1device.html", [
        [ "BMI088", "classrm_1_1device_1_1BMI088.html", "classrm_1_1device_1_1BMI088" ],
        [ "CanDevice", "classrm_1_1device_1_1CanDevice.html", "classrm_1_1device_1_1CanDevice" ],
        [ "Device", "classrm_1_1device_1_1Device.html", "classrm_1_1device_1_1Device" ],
        [ "DeviceManager", "classrm_1_1device_1_1DeviceManager.html", "classrm_1_1device_1_1DeviceManager" ],
        [ "DirectDriveMotor", "classrm_1_1device_1_1DirectDriveMotor.html", "classrm_1_1device_1_1DirectDriveMotor" ],
        [ "DjiMotor", "classrm_1_1device_1_1DjiMotor.html", "classrm_1_1device_1_1DjiMotor" ],
        [ "DjiMotorBase", "classrm_1_1device_1_1DjiMotorBase.html", "classrm_1_1device_1_1DjiMotorBase" ],
        [ "DmMotor", "classrm_1_1device_1_1DmMotor.html", "classrm_1_1device_1_1DmMotor" ],
        [ "DmMotorSettings", "structrm_1_1device_1_1DmMotorSettings.html", null ],
        [ "DmMotorSettings< DmMotorControlMode::kMit >", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kMit_01_4.html", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kMit_01_4" ],
        [ "DmMotorSettings< DmMotorControlMode::kSpeed >", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kSpeed_01_4.html", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kSpeed_01_4" ],
        [ "DmMotorSettings< DmMotorControlMode::kSpeedPosition >", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kSpeedPosition_01_4.html", "structrm_1_1device_1_1DmMotorSettings_3_01DmMotorControlMode_1_1kSpeedPosition_01_4" ],
        [ "DR16", "classrm_1_1device_1_1DR16.html", "classrm_1_1device_1_1DR16" ],
        [ "GkSupercap", "classrm_1_1device_1_1GkSupercap.html", "classrm_1_1device_1_1GkSupercap" ],
        [ "Go8010Motor", "classrm_1_1device_1_1Go8010Motor.html", "classrm_1_1device_1_1Go8010Motor" ],
        [ "HipnucImu", "classrm_1_1device_1_1HipnucImu.html", "classrm_1_1device_1_1HipnucImu" ],
        [ "HipnucImuCan", "classrm_1_1device_1_1HipnucImuCan.html", "classrm_1_1device_1_1HipnucImuCan" ],
        [ "HiWonderServo", "classrm_1_1device_1_1HiWonderServo.html", "classrm_1_1device_1_1HiWonderServo" ],
        [ "Ht04Motor", "classrm_1_1device_1_1Ht04Motor.html", "classrm_1_1device_1_1Ht04Motor" ],
        [ "IST8310", "classrm_1_1device_1_1IST8310.html", "classrm_1_1device_1_1IST8310" ],
        [ "JyMe02Can", "classrm_1_1device_1_1JyMe02Can.html", "classrm_1_1device_1_1JyMe02Can" ],
        [ "LkMotor", "classrm_1_1device_1_1LkMotor.html", "classrm_1_1device_1_1LkMotor" ],
        [ "Referee", "classrm_1_1device_1_1Referee.html", "classrm_1_1device_1_1Referee" ],
        [ "RefereeCmdId", "structrm_1_1device_1_1RefereeCmdId.html", null ],
        [ "RefereeCmdId< RefereeRevision::kNewV110 >", "structrm_1_1device_1_1RefereeCmdId_3_01RefereeRevision_1_1kNewV110_01_4.html", null ],
        [ "RefereeCmdId< RefereeRevision::kNewV120 >", "structrm_1_1device_1_1RefereeCmdId_3_01RefereeRevision_1_1kNewV120_01_4.html", null ],
        [ "RefereeCmdId< RefereeRevision::kV164 >", "structrm_1_1device_1_1RefereeCmdId_3_01RefereeRevision_1_1kV164_01_4.html", null ],
        [ "RefereeCmdId< RefereeRevision::kV170 >", "structrm_1_1device_1_1RefereeCmdId_3_01RefereeRevision_1_1kV170_01_4.html", null ],
        [ "RefereeProtocol", "structrm_1_1device_1_1RefereeProtocol.html", null ],
        [ "RefereeProtocol< RefereeRevision::kNewV110 >", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kNewV110_01_4.html", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kNewV110_01_4" ],
        [ "RefereeProtocol< RefereeRevision::kNewV120 >", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kNewV120_01_4.html", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kNewV120_01_4" ],
        [ "RefereeProtocol< RefereeRevision::kV164 >", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kV164_01_4.html", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kV164_01_4" ],
        [ "RefereeProtocol< RefereeRevision::kV170 >", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kV170_01_4.html", "structrm_1_1device_1_1RefereeProtocol_3_01RefereeRevision_1_1kV170_01_4" ],
        [ "RefereeProtocolMemoryMap", "structrm_1_1device_1_1RefereeProtocolMemoryMap.html", null ],
        [ "RefereeProtocolMemoryMap< RefereeRevision::kNewV110 >", "structrm_1_1device_1_1RefereeProtocolMemoryMap_3_01RefereeRevision_1_1kNewV110_01_4.html", null ],
        [ "RefereeProtocolMemoryMap< RefereeRevision::kNewV120 >", "structrm_1_1device_1_1RefereeProtocolMemoryMap_3_01RefereeRevision_1_1kNewV120_01_4.html", null ],
        [ "RefereeProtocolMemoryMap< RefereeRevision::kV164 >", "structrm_1_1device_1_1RefereeProtocolMemoryMap_3_01RefereeRevision_1_1kV164_01_4.html", null ],
        [ "RefereeProtocolMemoryMap< RefereeRevision::kV170 >", "structrm_1_1device_1_1RefereeProtocolMemoryMap_3_01RefereeRevision_1_1kV170_01_4.html", null ],
        [ "Sbus", "classrm_1_1device_1_1Sbus.html", "classrm_1_1device_1_1Sbus" ],
        [ "STP23L", "classrm_1_1device_1_1STP23L.html", "classrm_1_1device_1_1STP23L" ],
        [ "SuperCap", "classrm_1_1device_1_1SuperCap.html", "classrm_1_1device_1_1SuperCap" ],
        [ "UnitreeMotor", "classrm_1_1device_1_1UnitreeMotor.html", "classrm_1_1device_1_1UnitreeMotor" ],
        [ "VirtualDevice", "classrm_1_1device_1_1VirtualDevice.html", "classrm_1_1device_1_1VirtualDevice" ],
        [ "VT03", "classrm_1_1device_1_1VT03.html", "classrm_1_1device_1_1VT03" ],
        [ "ZdtStepper", "classrm_1_1device_1_1ZdtStepper.html", "classrm_1_1device_1_1ZdtStepper" ],
        [ "Znsv6T1", "classrm_1_1device_1_1Znsv6T1.html", "classrm_1_1device_1_1Znsv6T1" ]
      ] ],
      [ "hal", "namespacerm_1_1hal.html", [
        [ "detail", "namespacerm_1_1hal_1_1detail.html", [
          [ "ThrottledCan", "classrm_1_1hal_1_1detail_1_1ThrottledCan.html", "classrm_1_1hal_1_1detail_1_1ThrottledCan" ]
        ] ],
        [ "linux_", "namespacerm_1_1hal_1_1linux__.html", [
          [ "Serial", "classrm_1_1hal_1_1linux___1_1Serial.html", "classrm_1_1hal_1_1linux___1_1Serial" ],
          [ "SocketCan", "classrm_1_1hal_1_1linux___1_1SocketCan.html", "classrm_1_1hal_1_1linux___1_1SocketCan" ],
          [ "TimerFd", "classrm_1_1hal_1_1linux___1_1TimerFd.html", "classrm_1_1hal_1_1linux___1_1TimerFd" ]
        ] ],
        [ "stm32", "namespacerm_1_1hal_1_1stm32.html", [
          [ "BxCan", "classrm_1_1hal_1_1stm32_1_1BxCan.html", "classrm_1_1hal_1_1stm32_1_1BxCan" ],
          [ "I2cDevice", "classrm_1_1hal_1_1stm32_1_1I2cDevice.html", "classrm_1_1hal_1_1stm32_1_1I2cDevice" ],
          [ "Mcp2515", "classrm_1_1hal_1_1stm32_1_1Mcp2515.html", "classrm_1_1hal_1_1stm32_1_1Mcp2515" ],
          [ "Pin", "classrm_1_1hal_1_1stm32_1_1Pin.html", "classrm_1_1hal_1_1stm32_1_1Pin" ],
          [ "Spi", "classrm_1_1hal_1_1stm32_1_1Spi.html", "classrm_1_1hal_1_1stm32_1_1Spi" ],
          [ "SpiDevice", "classrm_1_1hal_1_1stm32_1_1SpiDevice.html", "classrm_1_1hal_1_1stm32_1_1SpiDevice" ],
          [ "Uart", "classrm_1_1hal_1_1stm32_1_1Uart.html", "classrm_1_1hal_1_1stm32_1_1Uart" ],
          [ "UartBase", "classrm_1_1hal_1_1stm32_1_1UartBase.html", "classrm_1_1hal_1_1stm32_1_1UartBase" ]
        ] ],
        [ "AsyncReadable", "classrm_1_1hal_1_1AsyncReadable.html", "classrm_1_1hal_1_1AsyncReadable" ],
        [ "AsyncSerialInterface", "classrm_1_1hal_1_1AsyncSerialInterface.html", null ],
        [ "AsyncTxSyncRxSerialInterface", "classrm_1_1hal_1_1AsyncTxSyncRxSerialInterface.html", null ],
        [ "AsyncWritable", "classrm_1_1hal_1_1AsyncWritable.html", "classrm_1_1hal_1_1AsyncWritable" ],
        [ "CanFrame", "structrm_1_1hal_1_1CanFrame.html", "structrm_1_1hal_1_1CanFrame" ],
        [ "CanInterface", "classrm_1_1hal_1_1CanInterface.html", "classrm_1_1hal_1_1CanInterface" ],
        [ "PinInterface", "classrm_1_1hal_1_1PinInterface.html", "classrm_1_1hal_1_1PinInterface" ],
        [ "PollingTimer", "classrm_1_1hal_1_1PollingTimer.html", "classrm_1_1hal_1_1PollingTimer" ],
        [ "SerialInterface", "classrm_1_1hal_1_1SerialInterface.html", null ],
        [ "SpiInterface", "classrm_1_1hal_1_1SpiInterface.html", "classrm_1_1hal_1_1SpiInterface" ],
        [ "SyncReadable", "classrm_1_1hal_1_1SyncReadable.html", "classrm_1_1hal_1_1SyncReadable" ],
        [ "SyncSerialInterface", "classrm_1_1hal_1_1SyncSerialInterface.html", null ],
        [ "SyncWritable", "classrm_1_1hal_1_1SyncWritable.html", "classrm_1_1hal_1_1SyncWritable" ],
        [ "TimerInterface", "classrm_1_1hal_1_1TimerInterface.html", "classrm_1_1hal_1_1TimerInterface" ]
      ] ],
      [ "modules", "namespacerm_1_1modules.html", [
        [ "buzzer_melody", "namespacerm_1_1modules_1_1buzzer__melody.html", [
          [ "Beeps", "classrm_1_1modules_1_1buzzer__melody_1_1Beeps.html", "classrm_1_1modules_1_1buzzer__melody_1_1Beeps" ],
          [ "Error", "classrm_1_1modules_1_1buzzer__melody_1_1Error.html", "classrm_1_1modules_1_1buzzer__melody_1_1Error" ],
          [ "SeeUAgain", "classrm_1_1modules_1_1buzzer__melody_1_1SeeUAgain.html", "classrm_1_1modules_1_1buzzer__melody_1_1SeeUAgain" ],
          [ "Silent", "classrm_1_1modules_1_1buzzer__melody_1_1Silent.html", "classrm_1_1modules_1_1buzzer__melody_1_1Silent" ],
          [ "Startup", "classrm_1_1modules_1_1buzzer__melody_1_1Startup.html", "classrm_1_1modules_1_1buzzer__melody_1_1Startup" ],
          [ "Success", "classrm_1_1modules_1_1buzzer__melody_1_1Success.html", "classrm_1_1modules_1_1buzzer__melody_1_1Success" ],
          [ "SuperMario", "classrm_1_1modules_1_1buzzer__melody_1_1SuperMario.html", "classrm_1_1modules_1_1buzzer__melody_1_1SuperMario" ],
          [ "TheLick", "classrm_1_1modules_1_1buzzer__melody_1_1TheLick.html", "classrm_1_1modules_1_1buzzer__melody_1_1TheLick" ],
          [ "Tone", "classrm_1_1modules_1_1buzzer__melody_1_1Tone.html", "classrm_1_1modules_1_1buzzer__melody_1_1Tone" ]
        ] ],
        [ "detail", "namespacerm_1_1modules_1_1detail.html", [
          [ "tuple_element_index", "structrm_1_1modules_1_1detail_1_1tuple__element__index.html", null ],
          [ "tuple_element_index< T, std::tuple< T, Ts... > >", "structrm_1_1modules_1_1detail_1_1tuple__element__index_3_01T_00_01std_1_1tuple_3_01T_00_01Ts_8_8_8_01_4_01_4.html", null ],
          [ "tuple_element_index< T, std::tuple< U, Ts... > >", "structrm_1_1modules_1_1detail_1_1tuple__element__index_3_01T_00_01std_1_1tuple_3_01U_00_01Ts_8_8_8_01_4_01_4.html", null ]
        ] ],
        [ "led_pattern", "namespacerm_1_1modules_1_1led__pattern.html", [
          [ "GreenBreath", "classrm_1_1modules_1_1led__pattern_1_1GreenBreath.html", "classrm_1_1modules_1_1led__pattern_1_1GreenBreath" ],
          [ "Off", "classrm_1_1modules_1_1led__pattern_1_1Off.html", "classrm_1_1modules_1_1led__pattern_1_1Off" ],
          [ "RedFlash", "classrm_1_1modules_1_1led__pattern_1_1RedFlash.html", "classrm_1_1modules_1_1led__pattern_1_1RedFlash" ],
          [ "RgbFlow", "classrm_1_1modules_1_1led__pattern_1_1RgbFlow.html", "classrm_1_1modules_1_1led__pattern_1_1RgbFlow" ]
        ] ],
        [ "accelMeasurement", "classrm_1_1modules_1_1accelMeasurement.html", "classrm_1_1modules_1_1accelMeasurement" ],
        [ "accelMeasurementModel", "classrm_1_1modules_1_1accelMeasurementModel.html", "classrm_1_1modules_1_1accelMeasurementModel" ],
        [ "AhrsInterface", "classrm_1_1modules_1_1AhrsInterface.html", "classrm_1_1modules_1_1AhrsInterface" ],
        [ "Angle", "classrm_1_1modules_1_1Angle.html", "classrm_1_1modules_1_1Angle" ],
        [ "BuzzerController", "classrm_1_1modules_1_1BuzzerController.html", "classrm_1_1modules_1_1BuzzerController" ],
        [ "BuzzerMelody", "classrm_1_1modules_1_1BuzzerMelody.html", "classrm_1_1modules_1_1BuzzerMelody" ],
        [ "BuzzerNote", "structrm_1_1modules_1_1BuzzerNote.html", "structrm_1_1modules_1_1BuzzerNote" ],
        [ "Control", "classrm_1_1modules_1_1Control.html", null ],
        [ "EkfAhrs", "classrm_1_1modules_1_1EkfAhrs.html", "classrm_1_1modules_1_1EkfAhrs" ],
        [ "EncoderCounter", "classrm_1_1modules_1_1EncoderCounter.html", "classrm_1_1modules_1_1EncoderCounter" ],
        [ "EulerAngle", "structrm_1_1modules_1_1EulerAngle.html", "structrm_1_1modules_1_1EulerAngle" ],
        [ "FdCanTransport", "classrm_1_1modules_1_1FdCanTransport.html", "classrm_1_1modules_1_1FdCanTransport" ],
        [ "ImuData6Dof", "structrm_1_1modules_1_1ImuData6Dof.html", "structrm_1_1modules_1_1ImuData6Dof" ],
        [ "ImuData9Dof", "structrm_1_1modules_1_1ImuData9Dof.html", "structrm_1_1modules_1_1ImuData9Dof" ],
        [ "KeyboardHandler", "classrm_1_1modules_1_1KeyboardHandler.html", "classrm_1_1modules_1_1KeyboardHandler" ],
        [ "KeyEvent", "structrm_1_1modules_1_1KeyEvent.html", "structrm_1_1modules_1_1KeyEvent" ],
        [ "MahonyAhrs", "classrm_1_1modules_1_1MahonyAhrs.html", "classrm_1_1modules_1_1MahonyAhrs" ],
        [ "MecanumChassis", "classrm_1_1modules_1_1MecanumChassis.html", "classrm_1_1modules_1_1MecanumChassis" ],
        [ "MotorCalibrator", "classrm_1_1modules_1_1MotorCalibrator.html", "classrm_1_1modules_1_1MotorCalibrator" ],
        [ "MotorPowerModel", "classrm_1_1modules_1_1MotorPowerModel.html", "classrm_1_1modules_1_1MotorPowerModel" ],
        [ "NoteDuration", "structrm_1_1modules_1_1NoteDuration.html", null ],
        [ "NoteFreq", "structrm_1_1modules_1_1NoteFreq.html", null ],
        [ "PID", "classrm_1_1modules_1_1PID.html", "classrm_1_1modules_1_1PID" ],
        [ "PollingTimer", "classrm_1_1modules_1_1PollingTimer.html", "classrm_1_1modules_1_1PollingTimer" ],
        [ "QuadOmniChassis", "classrm_1_1modules_1_1QuadOmniChassis.html", "classrm_1_1modules_1_1QuadOmniChassis" ],
        [ "Quaternion", "structrm_1_1modules_1_1Quaternion.html", "structrm_1_1modules_1_1Quaternion" ],
        [ "RgbLedController", "classrm_1_1modules_1_1RgbLedController.html", "classrm_1_1modules_1_1RgbLedController" ],
        [ "RgbLedPattern", "classrm_1_1modules_1_1RgbLedPattern.html", "classrm_1_1modules_1_1RgbLedPattern" ],
        [ "SequenceGenerator", "classrm_1_1modules_1_1SequenceGenerator.html", "classrm_1_1modules_1_1SequenceGenerator" ],
        [ "SequencePlayer", "classrm_1_1modules_1_1SequencePlayer.html", "classrm_1_1modules_1_1SequencePlayer" ],
        [ "SparseValueWatcher", "classrm_1_1modules_1_1SparseValueWatcher.html", "classrm_1_1modules_1_1SparseValueWatcher" ],
        [ "State", "classrm_1_1modules_1_1State.html", "classrm_1_1modules_1_1State" ],
        [ "SteeringChassis", "classrm_1_1modules_1_1SteeringChassis.html", "classrm_1_1modules_1_1SteeringChassis" ],
        [ "SystemModel", "classrm_1_1modules_1_1SystemModel.html", "classrm_1_1modules_1_1SystemModel" ],
        [ "ThresholdTrigger", "classrm_1_1modules_1_1ThresholdTrigger.html", "classrm_1_1modules_1_1ThresholdTrigger" ],
        [ "ThrottledPrioQueue", "classrm_1_1modules_1_1ThrottledPrioQueue.html", "classrm_1_1modules_1_1ThrottledPrioQueue" ],
        [ "TrajectoryLimiter", "classrm_1_1modules_1_1TrajectoryLimiter.html", "classrm_1_1modules_1_1TrajectoryLimiter" ],
        [ "TriSteeringChassis", "classrm_1_1modules_1_1TriSteeringChassis.html", "classrm_1_1modules_1_1TriSteeringChassis" ],
        [ "VofaPlotter", "classrm_1_1modules_1_1VofaPlotter.html", "classrm_1_1modules_1_1VofaPlotter" ]
      ] ],
      [ "hal_error", "classrm_1_1hal__error.html", "classrm_1_1hal__error" ],
      [ "ThreadPool", "classrm_1_1ThreadPool.html", "classrm_1_1ThreadPool" ]
    ] ]
];